---
- hosts: fairpos
  become: yes
  vars:
    probe_timeout: 360
  roles:
     - role: ansiblebit.oracle-java
       oracle_java_set_as_default: yes
     - { role: george.shuklin.reboot-if-needed-for-upgrade }
  tasks:
    - name: Update all DEB packages
      apt:
        update_cache: yes
        autoclean: yes
        autoremove: yes
        upgrade: dist

    # - name: Install Scala
    #   apt:
    #     deb: https://www.scala-lang.org/files/archive/scala-2.12.6.deb

    - name: Add SBT repository key
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: 2EE0EA64E40A89B84B2DF73499E82A75642AC823

    - name: Add SBT repository
      apt_repository:
        repo: 'deb https://dl.bintray.com/sbt/debian /'
        state: present

    - name: Install SBT
      apt:
        name: sbt
        update_cache: yes 

    - name: Clone Git repository
      git:
        repo: 'https://github.com/wavesplatform/Waves.git'
        dest: ~/waves
        version: node-129-fair-proof-of-stake

    - name: Build Waves
      command: sbt packageAll
      args:
        chdir: ~/waves
        
